language: go
go:
    - "1.12"
jobs:
    include:
        -   stage: Test and Build
            script:
                REVISION=${TRAVIS_COMMIT::7} make test && docker run -e BUILD_ARCH=amd64 -e REVISION=${TRAVIS_COMMIT::7} -e GIT_TAG=$(git describe --abbrev=0 --tags) -e DIST_DIR=/upload -v $(pwd)/_dist/:/upload --rm hephy/workflow-cli-dev:${TRAVIS_COMMIT::7} make build-all
